-- MySQL Script generated by MySQL Workbench
-- Sáb 08 Abr 2017 14:47:39 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cake_projectmanager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cake_projectmanager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cake_projectmanager` DEFAULT CHARACTER SET utf8 ;
USE `cake_projectmanager` ;

-- -----------------------------------------------------
-- Table `cake_projectmanager`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cake_projectmanager`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(40) CHARACTER SET 'ucs2' COLLATE 'ucs2_general_ci' NOT NULL,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `type` TINYINT(1) NOT NULL COMMENT 'type 1 -> developer\n\ntype 2 -> manager\n\ntype 3 -> company',
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cake_projectmanager`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cake_projectmanager`.`companies` (
  `id` INT NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_companies_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_companies_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `cake_projectmanager`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cake_projectmanager`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cake_projectmanager`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `client` VARCHAR(45) NOT NULL,
  `client_email` VARCHAR(45) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  `companies_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `companies_id`),
  INDEX `fk_projects_users1_idx` (`user_id` ASC),
  INDEX `fk_projects_companies1_idx` (`companies_id` ASC),
  CONSTRAINT `fk_projects_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cake_projectmanager`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_companies1`
    FOREIGN KEY (`companies_id`)
    REFERENCES `cake_projectmanager`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cake_projectmanager`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cake_projectmanager`.`teams` (
  `id` INT NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `project_id`),
  INDEX `fk_teams_users1_idx` (`user_id` ASC),
  INDEX `fk_teams_projects1_idx` (`project_id` ASC),
  CONSTRAINT `fk_teams_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cake_projectmanager`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teams_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `cake_projectmanager`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cake_projectmanager`.`activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cake_projectmanager`.`activities` (
  `id` INT NOT NULL,
  `task` TEXT(1024) NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `team_id` INT NOT NULL,
  PRIMARY KEY (`id`, `team_id`),
  INDEX `fk_activities_teams1_idx` (`team_id` ASC),
  CONSTRAINT `fk_activities_teams1`
    FOREIGN KEY (`team_id`)
    REFERENCES `cake_projectmanager`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
